AWSTemplateFormatVersion: 2010-09-09
Parameters:
  applicationStackS3Bucket:
    Type: String
    Description: Name of the S3 bucket containing the application.template.yml template file
    Default: ecommerce-store-1537366869949
  storeDBPassword:
    Type: String
    Description: Aurora master database password for store
    NoEcho: true

  shouldDeployService:
    Type: String
    Description: Should the ECS service be initialised
    AllowedValues:
        - true
        - false
    Default: false
Resources:
  store:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        parentStackName: !Ref AWS::StackName
        repositoryName: ecommerce-store/store
        shouldDeployService: !Ref shouldDeployService
        databasePassword: !Ref storeDBPassword
      TemplateURL: !Join [ '', [ 'https://s3.amazonaws.com/',!Ref applicationStackS3Bucket, '/store.template.yml'] ]

Outputs:
  LoadBalancerOutputstore:
    Description: The external DNS address of the load-balanancers
    Value: !GetAtt store.Outputs.LoadBalancerOutput

